node_js: 
- "0.10"
before_install: npm install -g grunt-cli
before_script: grunt
language: node_js
install: npm install
after_success: 
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git add client_side/*
- git commit --author "Travis CI <>" -m "Travis CI build
- git push https://github.com/hangy/Freebase.js.git
env: 
  global: 
    secure: PDwUAEy+DhHDaN2nNSgN9xtll0hNXEcI/Grh9H4ACAVGIY+/GDI0JvcS4CZ3wPLxOEoygzFdYjHk3iZleS+KZ+HRRV9PDDN4bLW7IQ98fVkzse64CmZhUnMMfBCsN5dPmdPDqz7PWZBaxMq5FuYyFbOU/37CP+fVcLgj80QcIak=
